### PR TITLE
Major changes

### PR DESCRIPTION
**Pull request by lfschenone**
Hi Matt, I was able to fix the two remaining issues, so I'm sending the the big commit. Cheers!

### CODE REVIEW

**Comment by lfschenone** [comment]
Hi Matt,
It's been some months since we last talked about this. I know that doing a full review of ~1000 lines can be difficult and it's not easy to find the time, but I need to know if you plan to do it this year. If you're not sure, I may consider continuing the project under a different name, but I really don't want to split efforts.
Regards,

**Comment by mattflaschen** [comment]
I'll do my best to merge it by this weekend.  I'll probably have to make some amendments, but I'll try to just do them myself unless I think it requires discussion (e.g. an architecture issue).

I apologize that I haven't been able to get to this earlier.

**Comment by mattflaschen** [comment]
Rebased to https://github.com/mattflaschen/proveit/tree/lfschenoneMajorChanges .

**Comment by mattflaschen** [comment]
In response to your questions and comments.

>  Regarding the TODO messages, I agree that they shouldn't be in the method documentation, but I think that the best place for them is the README.md file. Do you agree?

In some cases, I like to have inline TODOs (as regular comments, not method docs), but putting them in a README.md or HACKING.md is also fine (some projects do both, depending on how big a TODO it is).

> I'm having trouble with my localhost so I couldn't test the gadget, but the changes were few, simple and I double checked the syntax, so it should work ok.

I recommend you use https://www.mediawiki.org/wiki/MediaWiki-Vagrant for testing.  That will also make it easier for me to help you troubleshoot, if needed.

**Comment by mattflaschen** [comment]
I rebased the wrong version before.  Fixed now.

**Comment by mattflaschen** [comment]
I've started reviewing it and making small changes.  I'm half-way through Proveit_Wikipedia.js (done RawReference and everything above).

I've also fully reviewed all the other files you worked on (other than the main one).

Here are some notes:

When creating elements, you can still use multiple attributes in one attr call (using the object syntax), as long as .attr is called explicitly.  Also, it should not use self-closing tags (I realize the old version was using self-closing tags sometimes, but might as well fix it.

I'll go through and fix those.  E.g. for future reference it should be:

```
$( '<img>' ).attr( {
  'id': 'proveit-logo',
  'src': proveit.LOGO,
  'alt': 'ProveIt'
} );

And use .text(), rather than 'text':
```

You can also omit the string marks around the keys, but I left those for now (also something the old version was inconsistent on).

Regarding the summary, I plan to restore the behavior of adding the ProveIt part to the summary; let me know if you disagree or if you had particular problems with the old behavior.  Having a summary with *only* "(edited with [[User:ProveIt_GT|ProveIt]])" is not something we want to encourage (it doesn't answer the key questions like, "What reference did you add or change?" and  "Why?").  It is designed to be a supplement that makes people aware of ProveIt.

Finally, nice job. I like a lot of the architectural changes you've done.

**Comment by mattflaschen** [comment]
I didn't have a chance to do the second half of the file this weekend.  However, I'll try to finish it up one of the nights this week.I didn't have a chance to do the second half of the file this weekend.  However, I'll try to finish it up one of the nights this week.

**Comment by lfschenone** [comment]
I'm glad you found the time for reviewing and that you liked some of the architectural changes. I'm looking forward to the final review and merge, so we can move on to fixing issues and adding features together, as well as spreading the gadget to other Wikipedias.

I agree that we should avoid self-closing tags, it's cleaner. Also using text() makes sense, as the content of a tag is logically different from its attributes, so it should be distinguished in the syntax. Avoiding string marks around the keys would be fine too, I just prefer them because my code editor highlights certain keys differently (like 'class') if I don't use them.

As to the summary, I agree that the new method is worse than the previous one. We can fix it before or after the merge. I think it's the same, because it's not like we are about to update the code deployed at Wikipedia right after merging. However, let me know what you prefer and I'll be happy to comply. Cheers!

**Comment by mattflaschen** [comment]
Certain keys, such as 'class' (or ones that include a -), do require quotes, but others do not.

Personally, I'm fine with quoting only the ones that require it, but some people don't like that.  Anyway, not a blocker at all.

**Comment by mattflaschen** [comment]
Also, don't construct HTML like:

```
'<span class="label">' + label + '</span>: <span class="value">' + value + '</span>';
```

It's unsafe.  Use the jQuery methods.  You can still serialize it to HTML at the end.  (Trick, to get outerHTML equivalent, append to a div, then call jQuery's `.html()`).

(still reviewing)

**Comment by mattflaschen** [comment]
I'm done looking through and updating the code.  Latest version is at https://github.com/mattflaschen/proveit/commit/2dd8194224bc16ddacaab0d20f14feb16fbca37c .

Now I just need to do final testing, then merge.  Feel free to do testing of your own as well if you have time.

**Comment by lfschenone** [comment]
Awesome news Matt, thanks for the effort! I agree that we should always use jQuery methods for building HTML, I must have missed that one. Looking forward to the merge, let me know if I can help in any way.

**Comment by mattflaschen** [comment]
Thanks for all your work on this.  I'm glad to say it's merged.  I apologize that I didn't review it promptly.

I made a few additional changes after testing, including:

* Fixing how custom parameters worked (there was weirdness onclick due to the label)
* Removing the red coloring on input items
* Fixing a load order issue with the i18n templates.  If this isn't how you planned for it to work, let me know.

There's a couple more things I'd like to fix before we deploy it:

* The tab ordering on inputs when custom parameters are in use.
* The experience after you add or edit is a little weird.  It just leaves it open.  I think it should go back to the list view.

If you'd like to fix anything, let me know.  We can also discuss on Skype if you'd like.  I would also be glad to help you get a testing environment set up using MediaWiki-Vagrant.

It's neat that you can change types while editing now.  It would be nice if you could also do so while adding, before the initial insert.  This does not have to be done before deploy.

However, the commit is already very solid, so I thought now is the right time to merge it.  Going forward, let's try to keep commits smaller (certainly within the GitHub diff limits).

I will send you a direct email to discuss collaborating further.

**Comment by mattflaschen** [comment]
@lfschenone The summary change is up for review at https://github.com/proveit-js/proveit/pull/208 .

**Pull request closed without merging**
